[package]
name = "unirevlab-native-core"
version = "0.2.0"
edition = "2024"
license = "Apache-2.0"
description = "Memory-safe native analysis core for UniRevLab Security"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
sha2 = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
il2cpp_dumper = { git = "https://github.com/rodroidmods/il2cpp-dumper-rs", rev = "8bfb90229539833999e725c5cf6402a435b47f15" }

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21"
