"""Static text templates for the generated project ({{token}} placeholders)."""

from __future__ import annotations

GAME_HPP = """#pragma once
// ---------------------------------------------------------------------------
//  AUTO-GENERATED by modkit — {{app_name}}
//  target package: {{package}}   abi: {{abi}}   features: {{count}}
// ---------------------------------------------------------------------------
#include "modkit.hpp"

namespace game {

void install();
void apply(size_t index, double value);
void set_feature(size_t index, double value);
size_t feature_count();
const modkit::FeatureDef *features();
const char *feature_key(size_t index);
double peek_feature(size_t index);
bool set_feature_by_key(const char *key, double value);
double get_feature_by_key(const char *key);
const char *status_line();
void draw_features_ui();
void load_defaults();

constexpr size_t kFeatureCount = {{count}};

}  // namespace game
"""

UI_BLOCK = r"""
void draw_features_ui() {
#if MODKIT_HAS_IMGUI
    if (!ImGui::BeginTabBar("tabs", ImGuiTabBarFlags_FittingPolicyScroll)) {
        ImGui::TextUnformatted("no features yet");
        return;
    }
    const char *group = nullptr;
    bool open_tab = false;
    bool any_in_tab = false;
    for (size_t i = 0; i < kN; ++i) {
        const modkit::FeatureDef &f = g_features[i];
        if (!group || strcmp(group, f.group)) {
            if (open_tab) ImGui::EndTabItem();
            group = f.group;
            any_in_tab = false;
            open_tab = ImGui::BeginTabItem(group);
        }
        if (!open_tab) continue;
        any_in_tab = true;
        switch (f.kind) {
        case modkit::F_CONST_RETURN:
        case modkit::F_TOGGLE:
        case modkit::F_HOOK: {
            bool on = g_on[i];
            if (ImGui::Checkbox(f.label, &on)) {
                g_on[i] = on;
                apply(i, on ? (f.def != 0.0 ? f.def : 1.0) : 0.0);
            }
            break;
        }
        case modkit::F_VALUE_SET:
        case modkit::F_FIELD_WRITE:
        case modkit::F_STATIC_WRITE:
        case modkit::F_SLIDER: {
            if (f.hi - f.lo <= 1.0) {          // 0/1 range -> a plain switch, not a drag
                bool on = g_value[i] != 0.0;
                if (ImGui::Checkbox(f.label, &on)) apply(i, on ? (f.def != 0.0 ? f.def : 1.0) : 0.0);
                break;
            }
            float v = (float)g_value[i];
            {
                ImGui::PushID((int)i);
                ImGui::TextUnformatted(f.label);
                ImGui::SameLine();
                ImGui::SetNextItemWidth(180.0f);
                if (ImGui::DragFloat("##v", &v, 1.0f, (float)f.lo, (float)f.hi, "%.0f")) {
                    apply(i, v);
                    g_on[i] = v != 0.0;
                }
                ImGui::PopID();
            }
            break;
        }
        default:
            if (ImGui::Button(f.label)) apply(i, f.def);
            break;
        }
        if (f.flags & modkit::F_NEEDS_INSTANCE) {
            ImGui::SameLine();
            ImGui::TextColored(modkit::instance(f.slot) ? ImVec4(0.3f, 1.f, 0.4f, 1.f)
                                                         : ImVec4(1.f, 0.4f, 0.2f, 1.f),
                               "%s", modkit::instance(f.slot) ? "obj" : "no obj");
        }
    }
    if (open_tab) ImGui::EndTabItem();
    ImGui::EndTabBar();
#else
    // Console-only build: dump the feature list to logcat so `adb shell` still drives it.
    for (size_t i = 0; i < kN; ++i)
        LOGI("[%zu] %-34s %-12s = %g", i, g_features[i].key,
             g_features[i].label, g_value[i]);
#endif
}
"""

CMAKE = """cmake_minimum_required(VERSION 3.22)
project({{project}} CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

option(MODKIT_OVERLAY "draw the in-GL menu via the eglSwapBuffers hook" {{overlay}})
option(MODKIT_HAS_IMGUI "third_party/imgui is vendored" {{imgui}})
option(MODKIT_HAVE_DOBBY "link third_party/dobby instead of the built-in inline hooker" {{dobby}})
option(MODKIT_AUTOLOAD "start the runtime from an ELF constructor for DT_NEEDED injection" {{autoload}})

add_library({{project}} SHARED
    jni_main.cpp
    modkit.cpp
    game.cpp)

target_include_directories({{project}} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})

target_compile_definitions({{project}} PRIVATE
    MODKIT_TARGET_SO="{{target_so}}"
    MODKIT_TAG="{{tag}}"
    MODKIT_OVERLAY=$<BOOL:${MODKIT_OVERLAY}>
    MODKIT_HAS_IMGUI=$<BOOL:${MODKIT_HAS_IMGUI}>
    MODKIT_HAVE_DOBBY=$<BOOL:${MODKIT_HAVE_DOBBY}>
    MODKIT_AUTOLOAD=$<BOOL:${MODKIT_AUTOLOAD}>)

if(MODKIT_OVERLAY)
    target_sources({{project}} PRIVATE overlay.cpp)
endif()

if(MODKIT_HAS_IMGUI)
    file(GLOB IMGUI_SRC
        ${CMAKE_CURRENT_SOURCE_DIR}/../third_party/imgui/*.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/../third_party/imgui/backends/imgui_impl_opengl3.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/../third_party/imgui/backends/imgui_impl_opengl3_loader.h)
    target_sources({{project}} PRIVATE ${IMGUI_SRC})
    target_include_directories({{project}} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../third_party/imgui)
endif()

string(APPEND CMAKE_CXX_FLAGS " -D_GNU_SOURCE -Os -fvisibility=hidden -fno-rtti -Wall -Wno-unused-parameter"
       " -ffunction-sections -fdata-sections -fno-strict-aliasing")
string(APPEND CMAKE_SHARED_LINKER_FLAGS
       " -Wl,--gc-sections -Wl,--exclude-libs,ALL -Wl,-z,max-page-size=16384 -Wl,--build-id=sha1")

target_link_libraries({{project}} PRIVATE log android EGL GLESv3)

if(MODKIT_HAVE_DOBBY AND EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/../third_party/dobby/CMakeLists.txt)
    add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../third_party/dobby ${CMAKE_BINARY_DIR}/dobby)
    target_link_libraries({{project}} PRIVATE dobby)
endif()
"""

APP_GRADLE = """plugins {
    id 'com.android.application' version '8.5.2'
}

android {
    namespace '{{package}}.loader'
    compileSdk 34
    ndkVersion '26.3.11579264'

    defaultConfig {
        applicationId '{{package}}.loader'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '1.0'
        ndk { abiFilters '{{abi}}' }
        externalNativeBuild {
            cmake {
                arguments '-DANDROID_STL=c++_static',
                          '-DMODKIT_OVERLAY={{overlay}}',
                          '-DMODKIT_HAS_IMGUI=OFF',
                          '-DMODKIT_HAVE_DOBBY=OFF',
                          '-DMODKIT_AUTOLOAD={{autoload}}'
                abiFilters '{{abi}}'
            }
        }
    }

    externalNativeBuild {
        cmake { path 'src/main/cpp/CMakeLists.txt' }
    }

    sourceSets {
        main {
            java.srcDirs = ['src/main/java']
            assets.srcDirs = ['src/main/assets']
            manifest.srcFile 'src/main/AndroidManifest.xml'
        }
    }

    packagingOptions {
        jniLibs { useLegacyPackaging = false }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
    lint { abortOnError false }
}
"""

ROOT_GRADLE = """// top-level: nothing but the plugin classpath, the module is self-contained
plugins {
    id 'com.android.application' version '8.5.2' apply false
}
"""

SETTINGS_GRADLE = """pluginManagement {
    repositories { google(); mavenCentral(); gradlePluginPortal() }
}
dependencyResolutionManagement {
    repositories { google(); mavenCentral() }
}
rootProject.name = '{{app}}'
include ':app'
"""

MANIFEST = """<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <!-- Only the fallback console needs this; the in-GL menu draws inside the game. -->
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />

    <application
        android:label="{{app}}"
        android:icon="@mipmap/ic_launcher"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:allowBackup="false"
        android:hasCode="true">
        <activity
            android:name=".LoaderActivity"
            android:exported="true"
            android:excludeFromRecents="true"
            android:theme="@android:style/Theme.Material.Light">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
"""

MODKIT_JAVA = """package {{package}}.loader;

// Thin JNI facade over lib{{lib}}.so — the whole menu lives in native code.
public final class ModKit {

    private static volatile boolean loaded;

    private ModKit() {}

    public static synchronized void load() {
        if (loaded) return;
        System.loadLibrary("{{lib}}");
        loaded = true;
    }

    public static boolean ready() { return loaded && nativeReady(); }

    public static native void nativeInit();
    public static native boolean nativeReady();
    public static native String nativeStatus();
    public static native void nativeSetFeature(String key, double value);
    public static native double nativeGetFeature(String key);
    public static native void nativePushTouch(int action, float x, float y);
}
"""

LOADER_JAVA = """package {{package}}.loader;

import android.app.Activity;
import android.os.Bundle;
import android.text.InputType;
import android.view.MotionEvent;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;

/**
 * Console for the generated module: pick a feature key, type a value, apply.
 * The real menu is drawn inside the game (overlay.cpp) — this exists so a build
 * without ImGui is still operable, and so offsets can be probed one by one.
 */
public final class LoaderActivity extends Activity {

    private static final String[] KEYS = new String[] {
{{keys}}
    };

    private EditText value;
    private TextView status;

    @Override
    protected void onCreate(Bundle saved) {
        super.onCreate(saved);
        ModKit.load();
        ModKit.nativeInit();

        LinearLayout root = new LinearLayout(this);
        root.setOrientation(LinearLayout.VERTICAL);
        int pad = (int) (16 * getResources().getDisplayMetrics().density);
        root.setPadding(pad, pad, pad, pad);

        status = new TextView(this);
        status.setTextIsSelectable(true);
        root.addView(status);

        Button refresh = new Button(this);
        refresh.setText("refresh status");
        refresh.setOnClickListener(v -> status.setText(ModKit.nativeStatus()));
        root.addView(refresh);

        value = new EditText(this);
        value.setInputType(InputType.TYPE_CLASS_NUMBER | InputType.TYPE_NUMBER_FLAG_DECIMAL
                | InputType.TYPE_NUMBER_FLAG_SIGNED);
        value.setText("1");
        root.addView(value);

        for (String key : KEYS) {
            Button b = new Button(this);
            b.setAllCaps(false);
            b.setText(key);
            b.setOnClickListener(v -> {
                double d = parse(value.getText().toString());
                ModKit.nativeSetFeature(key, d);
                status.setText("set " + key + " = " + d + "\\n" + ModKit.nativeStatus());
            });
            b.setOnLongClickListener(v -> {
                value.setText(String.valueOf(ModKit.nativeGetFeature(key)));
                return true;
            });
            root.addView(b);
        }

        ScrollView sc = new ScrollView(this);
        sc.addView(root);
        setContentView(sc);
        status.setText(ModKit.nativeStatus());
    }

    @Override
    public boolean dispatchTouchEvent(MotionEvent ev) {
        // forwards to the in-game overlay when it runs on top of this console
        ModKit.nativePushTouch(ev.getActionMasked(), ev.getX(), ev.getY());
        return super.dispatchTouchEvent(ev);
    }

    private static double parse(String s) {
        try {
            return Double.parseDouble(s.trim());
        } catch (RuntimeException e) {
            return 1.0;
        }
    }
}
"""

BUILD_SH = """#!/usr/bin/env bash
# Standalone NDK build, no Gradle. Needs $ANDROID_NDK or any ndk/* under $ANDROID_HOME.
set -euo pipefail

ABI="${ABI:-arm64-v8a}"
API="${API:-26}"
NDK="${ANDROID_NDK:-$(ls -d "${ANDROID_HOME:-$HOME/Android/Sdk}"/ndk/* 2>/dev/null | sort -V | tail -1)}"
[ -d "$NDK" ] || { echo "NDK not found: set ANDROID_NDK" >&2; exit 1; }

case "$(uname -s)" in
  Linux)  HOST=linux-x86_64 ;;
  Darwin) HOST=darwin-x86_64 ;;
  *)      HOST=windows-x86_64 ;;
esac

SRC="$(cd "$(dirname "$0")" && pwd)"
OUT="$SRC/build/$ABI"

cmake -S "$SRC/app/src/main/cpp" -B "$OUT" -G Ninja \\
  -DCMAKE_TOOLCHAIN_FILE="$NDK/build/cmake/android.toolchain.cmake" \\
  -DANDROID_ABI="$ABI" \\
  -DANDROID_PLATFORM="android-$API" \\
  -DANDROID_STL=c++_static \\
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \\
  -DMODKIT_OVERLAY="${MODKIT_OVERLAY:-ON}" \\
  -DMODKIT_HAS_IMGUI="${MODKIT_HAS_IMGUI:-OFF}" \\
  -DMODKIT_HAVE_DOBBY="${MODKIT_HAVE_DOBBY:-OFF}" \\
  "${EXTRA_CMAKE:-}"

cmake --build "$OUT" -j"$(nproc 2>/dev/null || sysctl -n hw.ncpu)"

echo "lib{{lib}}.so -> $OUT/lib{{lib}}.so"
echo "push into the game's data dir, or:  adb install -r app.apk"
"""

README = """# {{app}} — generated offline mod module

Produced by `modkit` from the target's `global-metadata.dat` + `libil2cpp.so`
({{classes}} types / {{methods}} methods indexed, dump source: {{source}}).

| | |
|---|---|
| package | `{{package}}` |
| abi | `{{abi}}` |
| hooked module | `{{so}}` |
| metadata version | {{version}} |
| features | {{nfeat}} |
| instance-capture hooks | {{nhooks}} |

## How it works

1. `modkit` reads the dumper output and turns matched members into a feature table
   (`app/src/main/cpp/features.inc`) with the exact RVAs from the dump.
2. `jni_main.cpp` is loaded inside the game process. It waits for `{{so}}` to be mapped,
   takes the runtime base from `dl_iterate_phdr`, and translates every RVA at that base.
3. Three mechanisms, picked per feature by the analyzer:
   * **const_return** — the method prologue becomes `mov w0/x0, #imm; ret`
     (gold getters, damage, cooldowns). Original bytes are captured before patching,
     so the menu can switch it back off.
   * **value_set / toggle / action** — a direct native call to the managed method with
     the il2cpp ABI (`this` in x0). No patching, nothing to detect.
   * **field_write / static_write** — raw write at `this + off` or at the absolute rva of
     a static field's storage.
4. Instance members need an object. The generator installs a *capture hook* on a
   lifecycle method of the owning class (`Update`, `OnEnable`, …) and caches `this` in a
   slot; the menu shows `obj` / `no obj` next to those entries so you can see when the
   object has not been reached yet.
5. Menu rendering: hook `eglSwapBuffers` → draw ImGui with the game's GL context
   (`overlay.cpp`). With `-DMODKIT_HAS_IMGUI=OFF` the loader activity's console
   (feature key + value) is the fallback UI, which needs no permission at all.

## Build

```sh
# optional but recommended:
git clone --depth 1 https://github.com/ocornut/imgui third_party/imgui
git clone --depth 1 https://github.com/jmp03/Dobby third_party/dobby   # -DMODKIT_HAVE_DOBBY=ON

./build.sh                       # NDK only -> build/arm64-v8a/lib{{lib}}.so
# or  ./gradlew :app:assembleRelease
```

Then load it in the game process: repack the APK with the library in `lib/arm64-v8a/`
plus an `Application` hook that calls `System.loadLibrary("{{lib}}")`, or start it from
the loader app (`LoaderActivity`) for the console build.

## Feature map

| group | feature | kind | target | rva | conf |
|---|---|---|---|---|---|
{{rows}}

## Analyzer notes

{{notes}}

## Verifying on device

```sh
adb logcat -s {{app}} | head -60          # base, hooks, patch sites
adb push modkit.properties /sdcard/Android/data/{{package}}/files/
```

`modkit verify` re-reads the dump and the `.so` and checks every recorded RVA still
points at a plausible function prologue — run it after **any** game update, offsets move
between builds even when the logic does not.

## Limits you should know before wiring the last 10 %

* Only `arm64` encodings are emitted (`movz/movk/ret`, 16-byte patch windows). A 32-bit
  build needs a Thumb-2 encoder; `modkit build --abi armeabi-v7a` will tell you it is
  unsupported instead of emitting garbage.
* Constructors, property accessors with side effects and `System.Void` setters on
  reference-type fields are intentionally not auto-patched — they appear in
  `features.json` with `confidence` < 0.4 and are left out of the table.
* `const_return` on a method whose prologue is PC-relative cannot be inline-hooked with
  the built-in hooker; link Dobby for those.
* Nothing here is obfuscation-proof: if the target renames its symbols, the rules json
  (not the generator) is the place to teach modkit the new names.
"""
