from __future__ import annotations

from .base import ArtifactKind as A
from .base import EngineDescriptor as E
from .base import EngineKind as K
from .base import EngineState as S
from .registry import EngineRegistry


def build_default_registry() -> EngineRegistry:
    """Single source of truth for bundled engines and optional cross-check bridges."""
    engines = [
        E("apkset.inventory", "APK / split inventory", "1.0", K.INVENTORY, (A.APK, A.APK_SET), S.BUILTIN,
          "modkit.mobile.apkset", ("split-aware", "sha256", "ownership"), priority=10),
        E("runtime.profiler", "Universal Android runtime profiler", "1.0", K.ANALYZER, (A.APK, A.APK_SET), S.BUILTIN,
          "modkit.mobile.runtime_profiler", ("multi-runtime", "engine-detection", "abi-inventory", "split-aware", "unknown-runtime-fallback"),
          priority=11, notes="Detects all coexisting runtimes instead of selecting one primary framework."),
        E("runtime.engine-router", "Multi-runtime engine router", "1.0", K.INVENTORY, (A.APK, A.APK_SET), S.BUILTIN,
          "modkit.mobile.engine_router", ("multi-engine-plan", "coverage-gaps", "honest-fallback", "abi-aware"),
          priority=12, notes="Routes every detected runtime to bundled analyzers and records missing specialized backends explicitly."),
        E("protection.deobfuscator", "Deobfuscation / protection profiler", "1.0", K.ANALYZER, (A.APK, A.APK_SET, A.DEX, A.ELF, A.RESOURCE), S.BUILTIN,
          "modkit.mobile.deobfuscator", ("identifier-normalization", "stable-aliases", "packer-markers", "dynamic-loading", "anti-debug", "integrity", "opaque-assets"),
          priority=18, notes="Passive fail-closed deobfuscation planning. Never invents original names or treats entropy alone as proof of encryption."),
        E("apktool.android", "Apktool embedded decoder", "2.12.1", K.DECODER, (A.APK, A.APK_SET, A.MANIFEST, A.RESOURCE, A.DEX), S.BUILTIN,
          "android:dev.modkit.mobile.ApktoolEngine", ("resources", "binary-xml", "arsc", "smali", "assets", "split-aware", "private-workspace"),
          priority=15, license_note="Apache-2.0", notes="Runs inside the Android app; no desktop Apktool or manual import is required."),
        E("resources.decoder", "Android resources decoder", "1.0", K.DECODER, (A.MANIFEST, A.RESOURCE), S.BUILTIN,
          "modkit.mobile.engine:resource analysis", ("binary-xml", "arsc", "manifest", "resources"), priority=20),
        E("dex.structural", "DEX structural analyzer", "1.0", K.ANALYZER, (A.DEX,), S.BUILTIN,
          "modkit.reworkspace.dex", ("classes", "fields", "methods", "code-offsets", "xrefs"), priority=20),
        E("jadx.android", "JADX Android decompiler", "1.5.6", K.DECOMPILER, (A.APK, A.APK_SET, A.DEX, A.RESOURCE), S.BUILTIN,
          "android:dev.modkit.mobile.DecompilerEngine", ("java-view", "smali-view", "resources", "xrefs", "full-export"),
          fallback_for=("dex.structural",), priority=30, license_note="Apache-2.0",
          notes="Java-like output is a decompiler view; DEX/Smali remains authoritative when recovery fails."),
        E("elf.universal-inventory", "Universal Android ELF inventory", "1.0", K.ANALYZER, (A.ELF, A.APK, A.APK_SET), S.BUILTIN,
          "modkit.mobile.native_inventory", ("elf32", "elf64", "arm", "arm64", "x86", "x86_64", "abi-validation", "split-aware"),
          priority=19, notes="Architecture-neutral inventory; deep instruction/data-flow remains architecture-specific."),
        E("native.portable-embedded", "Portable ELF symbol/relocation analyzer", "1.0", K.ANALYZER, (A.ELF, A.APK, A.APK_SET), S.BUILTIN,
          "modkit.mobile.native_portable", ("elf32", "elf64", "symbols", "imports", "exports", "rel", "rela", "relocation-symbol-refs", "jni-markers"),
          priority=20, notes="Architecture-neutral exact ELF metadata/relocation evidence. Does not claim CFG or instruction data-flow."),
        E("native.arm32-deep-embedded", "ARMv7 / Thumb control-flow analyzer", "1.0", K.DISASSEMBLER, (A.ELF, A.APK, A.APK_SET), S.BUILTIN,
          "modkit.mobile.arm32_deep", ("armv7", "a32", "thumb", "thumb2", "direct-calls", "branches", "symbol-bounded-cfg-evidence"),
          priority=21, notes="Conservative STT_FUNC-bounded ARM/Thumb control-flow. Stripped-region guessing and unresolved indirect-target claims are disabled."),
        E("elf.static", "ELF / ARM64 analyzer", "1.0", K.DISASSEMBLER, (A.ELF,), S.BUILTIN,
          "modkit.reworkspace.native", ("elf", "symbols", "strings", "arm64", "rva", "xrefs"), priority=20),
        E("native.deep-embedded", "Embedded ARM64 call/xref analyzer", "1.1", K.ANALYZER, (A.ELF,), S.BUILTIN,
          "modkit.mobile.native_deep", ("function-rva", "direct-bl", "tail-b", "absolute-thunks", "indirect-slot-blr", "adrp-add-xrefs", "semantic-strings", "call-graph", "split-aware"),
          priority=21, notes="Runs locally over app-owned ARM64 ELF files; exact static targets and structural-only indirect slots are kept distinct; Ghidra/Rizin are optional corroboration only."),
        E("il2cpp.rodroid", "Rodroid IL2CPP reconstructor", "7", K.RECONSTRUCTOR, (A.IL2CPP, A.ELF), S.BUILTIN,
          "android:dev.modkit.mobile.RodroidRunner", ("metadata", "types", "fields", "methods", "rva", "offsets"), priority=20),
        E("unity.discovery", "Unity / IL2CPP discovery", "1.0", K.ANALYZER, (A.APK, A.APK_SET, A.IL2CPP, A.UNITY_ASSET), S.BUILTIN,
          "modkit.mobile.unityscan", ("engine-detection", "metadata-pair", "addressables", "unity-assets"), priority=20),
        E("lua.static", "Lua / xLua / SLua analyzer", "1.0", K.DECOMPILER, (A.LUA,), S.BUILTIN,
          "modkit.mobile.artifact_families", ("source", "bytecode-header", "version", "function-index", "strings", "split-aware"), priority=25,
          notes="Plain Lua source is recoverable; compiled/encrypted chunks remain explicitly bytecode/opaque."),
        E("lua.bytecode-embedded", "Embedded Lua bytecode structural disassembler", "1.0", K.DISASSEMBLER, (A.LUA,), S.BUILTIN,
          "modkit.mobile.lua_deep", ("puc-lua-5.1", "puc-lua-5.2", "puc-lua-5.3", "prototype-tree", "constants", "instructions", "debug-metadata", "xlua-slua-detection", "split-aware"),
          priority=26, notes="Standard PUC Lua chunks are decoded statically. LuaJIT, Lua 5.4 and custom/encrypted xLua/SLua containers remain structural or opaque evidence rather than guessed source."),
        E("javascript.static", "JavaScript / React Native bundle analyzer", "1.0", K.DECOMPILER, (A.JAVASCRIPT,), S.BUILTIN,
          "modkit.mobile.artifact_families", ("source", "bundle", "function-index", "react-native-markers", "split-aware"), priority=25),
        E("jsc.deep-embedded", "JavaScriptCore / React Native JSC analyzer", "1.0", K.ANALYZER, (A.JAVASCRIPT, A.APK, A.APK_SET, A.ELF), S.BUILTIN,
          "modkit.mobile.jsc_deep", ("source-bundle", "jsc-binary-inventory", "function-index", "semantic-strings", "native-runtime", "split-aware"),
          priority=26, notes="Indexes source bundles and binary JSC evidence without claiming original source from version-specific bytecode."),
        E("hermes.static", "Hermes bytecode static analyzer", "1.0", K.DISASSEMBLER, (A.HERMES,), S.BUILTIN,
          "modkit.mobile.artifact_families", ("hbc-inventory", "strings", "bytecode-metadata", "split-aware"), priority=25,
          notes="Does not falsely claim original JavaScript recovery from HBC."),
        E("hermes.deep-embedded", "Hermes HBC embedded disassembler", "hbctool-0.1.5", K.DECOMPILER, (A.HERMES, A.JAVASCRIPT), S.BUILTIN,
          "modkit.mobile.hermes_deep", ("hbc-header", "function-table", "instruction-disassembly", "string-table", "versions-59-62-74-76-84-85"),
          priority=26, license_note="MIT", notes="Runs inside Chaquopy; unsupported HBC versions fall back to hermes.static."),
        E("flutter.static", "Flutter / Dart AOT artifact analyzer", "1.0", K.RECONSTRUCTOR, (A.FLUTTER, A.ELF), S.BUILTIN,
          "modkit.mobile.artifact_families", ("flutter-assets", "snapshots", "libapp", "libflutter", "dart-aot", "native-correlation"), priority=25,
          notes="AOT/snapshot recovery level is reported honestly; original Dart source is not claimed."),
        E("flutter.aot-embedded", "Embedded Flutter/Dart AOT recovery", "1.0", K.RECONSTRUCTOR, (A.FLUTTER, A.ELF), S.BUILTIN,
          "modkit.mobile.flutter_deep", ("libapp-aot", "snapshot-metadata", "package-strings", "route-strings", "native-correlation", "split-aware"),
          priority=26, notes="Correlates Flutter assets/snapshots with embedded ARM64 analysis; it does not claim original Dart source recovery."),
        E("cocos.static", "Cocos2d-x / Cocos Creator analyzer", "1.0", K.ANALYZER, (A.COCOS, A.JAVASCRIPT, A.ELF), S.BUILTIN,
          "modkit.mobile.artifact_families", ("engine-detection", "project-js", "jsc", "native-engine", "split-aware"), priority=25),
        E("cocos.deep-embedded", "Embedded Cocos script/native correlator", "1.0", K.ANALYZER, (A.COCOS, A.JAVASCRIPT, A.LUA, A.ELF), S.BUILTIN,
          "modkit.mobile.cocos_deep", ("script-native-correlation", "jsb-bridge-symbols", "exact-native-rva", "control-flow-evidence", "split-aware"),
          priority=26, notes="Correlates Cocos script symbols with native bridge/symbol evidence statically. Native symbol RVA is exact when present; script runtime addresses and indirect runtime targets are never invented."),
        E("dotnet.static", ".NET / Mono managed artifact inventory", "1.0", K.ANALYZER, (A.DOTNET, A.APK, A.APK_SET), S.BUILTIN,
          "modkit.mobile.artifact_families", ("managed-assembly-inventory", "unity-mono-markers", "split-aware", "bounded-sampling"),
          priority=27, notes="Inventories managed assemblies and runtime markers; deep CIL/NativeAOT reconstruction remains a separate backend."),
        E("dotnet.metadata-embedded", ".NET / Mono CLI metadata recovery", "1.0", K.RECONSTRUCTOR, (A.DOTNET, A.APK, A.APK_SET), S.BUILTIN,
          "modkit.mobile.dotnet_deep", ("cli-metadata-root", "metadata-streams", "table-row-counts", "strings-heap", "user-strings", "semantic-correlation"),
          priority=28, notes="Recovers ECMA-335 metadata structure and strings without claiming original C# source or NativeAOT reconstruction."),
        E("unreal.static", "Unreal cooked artifact inventory", "1.0", K.ANALYZER, (A.UNREAL, A.APK, A.APK_SET), S.BUILTIN,
          "modkit.mobile.artifact_families", ("pak", "iostore", "uasset", "uexp", "bounded-sampling", "split-aware"),
          priority=27, notes="Inventories cooked Unreal containers/assets without claiming UObject/Blueprint semantic reconstruction."),
        E("unreal.deep-embedded", "Unreal cooked/reflection correlator", "1.0", K.RECONSTRUCTOR, (A.UNREAL, A.ELF, A.APK, A.APK_SET), S.BUILTIN,
          "modkit.mobile.unreal_deep", ("uasset-sidecars", "iostore-pairs", "pak-footer-markers", "reflection-names", "semantic-strings", "split-aware"),
          priority=28, notes="Correlates cooked topology and reflection/name evidence without claiming Blueprint or native source recovery."),
        E("godot.static", "Godot artifact inventory", "1.0", K.ANALYZER, (A.GODOT, A.APK, A.APK_SET), S.BUILTIN,
          "modkit.mobile.artifact_families", ("pck", "gdscript-source", "scene-resource", "split-aware"),
          priority=27),
        E("godot.deep-embedded", "Godot PCK / scene graph recovery", "1.0", K.RECONSTRUCTOR, (A.GODOT, A.APK, A.APK_SET), S.BUILTIN,
          "modkit.mobile.godot_deep", ("pck-header", "gdscript-structure", "text-scene-graph", "external-resources", "semantic-nodes", "split-aware"),
          priority=28, notes="Parses text scenes/resources and GDScript structure; binary/encrypted PCK content remains explicit review evidence."),
        E("defold.static", "Defold artifact inventory", "1.0", K.ANALYZER, (A.DEFOLD, A.APK, A.APK_SET), S.BUILTIN,
          "modkit.mobile.artifact_families", ("archive", "manifest", "native-engine", "split-aware"),
          priority=27),
        E("defold.deep-embedded", "Defold archive/resource correlator", "1.0", K.RECONSTRUCTOR, (A.DEFOLD, A.APK, A.APK_SET, A.ELF), S.BUILTIN,
          "modkit.mobile.defold_deep", ("archive-pair", "manifest", "projectc", "resource-paths", "semantic-strings", "split-aware"),
          priority=28, notes="Correlates compiled archive topology/resources without claiming original Lua source."),
        E("qt.qml-static", "Qt / QML artifact inventory", "1.0", K.ANALYZER, (A.QML, A.APK, A.APK_SET), S.BUILTIN,
          "modkit.mobile.artifact_families", ("qml-source", "qml-bytecode", "rcc", "split-aware"),
          priority=27),
        E("qt.qml-deep-embedded", "Qt / QML structural analyzer", "1.0", K.RECONSTRUCTOR, (A.QML, A.APK, A.APK_SET, A.ELF), S.BUILTIN,
          "modkit.mobile.qml_deep", ("imports", "components", "properties", "signals", "functions", "rcc-header", "compiled-qml-inventory"),
          priority=28, notes="Parses source QML structure and inventories compiled QML/RCC without claiming source recovery from bytecode."),
        E("webassembly.static", "WebAssembly artifact inventory", "1.0", K.DISASSEMBLER, (A.WEBASSEMBLY, A.APK, A.APK_SET), S.BUILTIN,
          "modkit.mobile.artifact_families", ("wasm-magic", "bytecode-inventory", "split-aware"),
          priority=27, notes="Structural inventory only; original source is never claimed."),
        E("webassembly.deep-embedded", "WebAssembly section/export parser", "1.0", K.DISASSEMBLER, (A.WEBASSEMBLY, A.APK, A.APK_SET), S.BUILTIN,
          "modkit.mobile.wasm_deep", ("module-header", "section-directory", "vector-counts", "custom-sections", "exports", "semantic-exports"),
          priority=28, notes="Parses standard WASM module structure and exports without executing code or claiming source recovery."),
        E("semantic.gameplay", "Gameplay semantic evidence", "1.0", K.SEMANTIC, (A.DEX, A.IL2CPP, A.ELF, A.RESOURCE, A.LUA, A.JAVASCRIPT, A.COCOS), S.BUILTIN,
          "modkit.mobile.gameplay", ("ownership", "evidence-graph", "health", "damage", "currency", "movement"), priority=40),
        E("security.passive", "Passive security surface analyzer", "1.0", K.SECURITY, (A.APK, A.APK_SET, A.DEX, A.ELF, A.RESOURCE, A.LUA, A.JAVASCRIPT), S.BUILTIN,
          "modkit.mobile.security_scan", ("network", "tls", "crypto", "auth", "storage", "webview"), priority=40,
          safe_defaults={"active_network": False, "secret_extraction": False}),
        E("runtime.root-procfs", "Root procfs runtime session", "1.0", K.RUNTIME, (A.PROCESS,), S.BUILTIN,
          "android:dev.modkit.mobile.RootProcessEngine", ("root-probe", "process-list", "status", "maps", "threads", "modules"), priority=20,
          notes="Explicit user action; read-only runtime observation by default."),
        E("report.evidence-bundle", "Evidence Bundle exporter", "1.0", K.REPORTER, (A.EVIDENCE,), S.BUILTIN,
          "android:dev.modkit.mobile.EvidenceBundleExporter", ("json", "jsonl", "hashes", "toolchain", "runtime-snapshot"), priority=20),

        # Optional cross-check adapters. They are not required for a normal in-app analysis.
        E("apktool.bridge", "Apktool external cross-check bridge", "1.0", K.DECODER, (A.APK, A.APK_SET, A.RESOURCE), S.ENTRY_POINT,
          "adapter:apktool", ("decoded-tree-import", "smali-import", "rebuild-output-import"), priority=80, license_note="Apache-2.0",
          notes="Compatibility/corroboration only. apktool.android is the primary embedded decoder."),
        E("ghidra.bridge", "Ghidra native analysis bridge", "1.0", K.DECOMPILER, (A.ELF,), S.ENTRY_POINT,
          "adapter:ghidra", ("symbol-import", "pseudocode-import", "cfg-import", "xref-import", "evidence-export"), priority=80, license_note="Apache-2.0",
          notes="Optional corroboration. native.deep-embedded is the primary in-app native call/xref backend."),
        E("rizin.bridge", "Rizin analysis bridge", "1.0", K.DISASSEMBLER, (A.ELF, A.DEX), S.ENTRY_POINT,
          "adapter:rizin", ("disassembly-import", "cfg-import", "xref-import", "evidence-export"), priority=80,
          notes="Optional corroboration. Native static analysis does not depend on Rizin."),
        E("cpp2il.bridge", "Cpp2IL IL2CPP cross-check bridge", "1.0", K.RECONSTRUCTOR, (A.IL2CPP,), S.ENTRY_POINT,
          "adapter:cpp2il", ("managed-il-import", "metadata-import", "rodroid-cross-check"), priority=80),
        E("flutter.deep-bridge", "Deep Flutter/Dart external cross-check", "1.0", K.RECONSTRUCTOR, (A.FLUTTER, A.ELF), S.ENTRY_POINT,
          "adapter:flutter-deep", ("symbol-map-import", "function-map-import", "snapshot-cross-check"), priority=80,
          notes="Optional corroboration. flutter.aot-embedded is the primary in-app AOT recovery backend."),
        E("hermes.deep-bridge", "Hermes external cross-check bridge", "1.0", K.DECOMPILER, (A.HERMES, A.JAVASCRIPT), S.ENTRY_POINT,
          "adapter:hermes-deep", ("hbc-disassembly-import", "function-map-import", "source-map-import"), priority=80,
          notes="Compatibility/corroboration only. hermes.deep-embedded is primary for supported HBC versions."),
        E("frida.local-bridge", "Frida local runtime bridge", "1.0", K.RUNTIME, (A.PROCESS,), S.OPTIONAL,
          "adapter:frida", ("server-detection", "attach-contract", "module-events", "trace-import"), priority=85,
          notes="Optional rooted local runtime pack; static analysis and root-procfs do not depend on it."),
        E("ptrace.bridge", "Native debugger/ptrace bridge", "1.0", K.RUNTIME, (A.PROCESS,), S.ENTRY_POINT,
          "adapter:ptrace", ("attach-contract", "register-snapshot-import", "breakpoint-evidence-import"), priority=85),

        # Compatibility IDs are retained so saved reports/automation from the pre-1.0 registry keep
        # resolving. They are aliases only and remain explicitly non-bundled.
        E("ghidra.external", "Ghidra external compatibility alias", "1.0", K.DECOMPILER, (A.ELF,), S.ENTRY_POINT,
          "compat-alias:ghidra.bridge", ("compatibility-alias",), priority=95, notes="Use ghidra.bridge for new integrations."),
        E("rizin.external", "Rizin external compatibility alias", "1.0", K.DISASSEMBLER, (A.ELF, A.DEX), S.ENTRY_POINT,
          "compat-alias:rizin.bridge", ("compatibility-alias",), priority=95, notes="Use rizin.bridge for new integrations."),
        E("frida.external", "Frida external compatibility alias", "1.0", K.RUNTIME, (A.PROCESS,), S.OPTIONAL,
          "compat-alias:frida.local-bridge", ("compatibility-alias",), priority=95, notes="Use frida.local-bridge for new integrations."),
        E("flutter.external", "Flutter external compatibility alias", "1.0", K.RECONSTRUCTOR, (A.FLUTTER, A.ELF), S.ENTRY_POINT,
          "compat-alias:flutter.deep-bridge", ("compatibility-alias",), priority=95, notes="Use flutter.deep-bridge for new integrations."),
        E("hermes.external", "Hermes external compatibility alias", "1.0", K.DECOMPILER, (A.HERMES, A.JAVASCRIPT), S.ENTRY_POINT,
          "compat-alias:hermes.deep-bridge", ("compatibility-alias",), priority=95, notes="Use hermes.deep-bridge for new integrations."),
    ]
    return EngineRegistry(engines)
