-- UniRevLab Coordinator PostgreSQL baseline schema v3.
-- Apply inside a dedicated database/schema with UTF-8 and UTC application timestamps.
BEGIN;

CREATE TABLE IF NOT EXISTS assessments (
    id UUID PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL CHECK (length(status) BETWEEN 1 AND 64),
    request_json JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS ghidra_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id UUID NOT NULL REFERENCES assessments(id) ON DELETE CASCADE,
    library_entry TEXT NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL,
    result_sha256 CHAR(64) NOT NULL CHECK (result_sha256 ~ '^[0-9a-f]{64}$'),
    payload_json JSONB NOT NULL,
    UNIQUE(assessment_id, library_entry, result_sha256)
);
CREATE INDEX IF NOT EXISTS idx_ghidra_assessment_library_revision
    ON ghidra_results(assessment_id, library_entry, id DESC);

CREATE TABLE IF NOT EXISTS coordinator_meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    actor_fingerprint TEXT NOT NULL,
    event_type TEXT NOT NULL,
    assessment_id UUID NULL,
    object_sha256 CHAR(64) NULL CHECK (object_sha256 IS NULL OR object_sha256 ~ '^[0-9a-f]{64}$'),
    event_json JSONB NOT NULL,
    previous_hash CHAR(64) NULL CHECK (previous_hash IS NULL OR previous_hash ~ '^[0-9a-f]{64}$'),
    event_hash CHAR(64) NOT NULL UNIQUE CHECK (event_hash ~ '^[0-9a-f]{64}$')
);
CREATE INDEX IF NOT EXISTS idx_audit_assessment_id ON audit_events(assessment_id, id ASC);

INSERT INTO coordinator_meta(key, value) VALUES ('schema_version', '3')
ON CONFLICT(key) DO UPDATE SET value = EXCLUDED.value;

COMMIT;
