#pragma once
// ---------------------------------------------------------------------------
//  AUTO-GENERATED by modkit — neondrift
//  target package: com.neondrift.game   abi: arm64-v8a   features: 21
// ---------------------------------------------------------------------------
#include "modkit.hpp"

namespace game {

void install();
void apply(size_t index, double value);
void set_feature(size_t index, double value);
size_t feature_count();
const modkit::FeatureDef *features();
const char *feature_key(size_t index);
double peek_feature(size_t index);
bool set_feature_by_key(const char *key, double value);
double get_feature_by_key(const char *key);
const char *status_line();
void draw_features_ui();
void load_defaults();

constexpr size_t kFeatureCount = 21;

}  // namespace game
