// ---------------------------------------------------------------------------
//  AUTO-GENERATED by modkit for neondrift. Regenerate, do not hand-edit;
//  custom callbacks belong in a separate TU that includes game.hpp.
// ---------------------------------------------------------------------------
#include "game.hpp"

#include <atomic>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <mutex>

#if MODKIT_HAS_IMGUI
#include "imgui.h"
#endif

namespace game {
namespace {
constexpr size_t kN = 21;
double g_value[kN == 0 ? 1 : kN];
bool g_on[kN == 0 ? 1 : kN];
uint8_t g_saved[kN == 0 ? 1 : kN][24];
bool g_saved_ok[kN == 0 ? 1 : kN];
bool g_installed = false;

void *g_orig_inst_GameOptions = nullptr;
void *g_orig_inst_PlayerSave = nullptr;
void *g_orig_inst_PlayerController = nullptr;
void *g_hk3_orig = nullptr;
void *g_hk18_orig = nullptr;
}  // namespace

// the tables in features.inc name these, and the callbacks below name the tables,
// so both sides need a declaration first
static void rep_inst_GameOptions(void *_this);
static void rep_inst_PlayerSave(void *_this);
static void rep_inst_PlayerController(void *_this);
static void hk_3(void *_this, int32_t a0);
static void hk_18(void *_this, float a0);

#include "features.inc"

namespace off {  // one constant per addressable managed member
    constexpr uint32_t Weapon_get_Ammo = 0x1210;  // NeonDrift.Play.Weapon::get_Ammo
    constexpr uint32_t Weapon_GetCooldown = 0x1240;  // NeonDrift.Play.Weapon::GetCooldown
    constexpr uint32_t Weapon_GetDamage = 0x1230;  // NeonDrift.Play.Weapon::GetDamage
    constexpr uint32_t EnemySpawner_Spawn = 0x1310;  // NeonDrift.Play.EnemySpawner::Spawn
    constexpr uint32_t GameOptions_set_Coins = 0x1410;  // NeonDrift.Save.GameOptions::set_Coins
    constexpr uint32_t GameOptions_get_Coins = 0x1400;  // NeonDrift.Save.GameOptions::get_Coins
    constexpr uint32_t PlayerSave_set_Gems = 0x1070;  // NeonDrift.Save.PlayerSave::set_Gems
    constexpr uint32_t PlayerSave_get_Gems = 0x1060;  // NeonDrift.Save.PlayerSave::get_Gems
    constexpr uint32_t PlayerSave_set_Gold = 0x1050;  // NeonDrift.Save.PlayerSave::set_Gold
    constexpr uint32_t PlayerSave_get_Gold = 0x1040;  // NeonDrift.Save.PlayerSave::get_Gold
    constexpr uint32_t PlayerController_set_MoveSpeed = 0x1130;  // NeonDrift.Play.PlayerController::set_MoveSpeed
    constexpr uint32_t PlayerController_get_MoveSpeed = 0x1120;  // NeonDrift.Play.PlayerController::get_MoveSpeed
    constexpr uint32_t PlayerSave_set_Level = 0x1090;  // NeonDrift.Save.PlayerSave::set_Level
    constexpr uint32_t PlayerSave_get_Level = 0x1080;  // NeonDrift.Save.PlayerSave::get_Level
    constexpr uint32_t PlayerSave_s_debugUnlocks = 0x5010;  // NeonDrift.Save.PlayerSave::s_debugUnlocks
    constexpr uint32_t PlayerController_get_IsGodMode = 0x1150;  // NeonDrift.Play.PlayerController::get_IsGodMode
    constexpr uint32_t PlayerController_set_IsGodMode = 0x1140;  // NeonDrift.Play.PlayerController::set_IsGodMode
    constexpr uint32_t PlayerController_TakeDamage = 0x1110;  // NeonDrift.Play.PlayerController::TakeDamage
    constexpr uint32_t PlayerSave_Save = 0x10a0;  // NeonDrift.Save.PlayerSave::Save
    constexpr uint32_t GameOptions_UnlockAllTracks = 0x1420;  // instance capture
    constexpr uint32_t PlayerController_Update = 0x1100;  // instance capture
}  // namespace off

// ---- instance capture: NeonDrift.Save.GameOptions.UnlockAllTracks @ rva 0x1420
static void rep_inst_GameOptions(void *_this) {
    modkit::set_instance(0, _this);
    if (auto fn = reinterpret_cast<void (*)(void *)>(g_orig_inst_GameOptions)) fn(_this);
}

// ---- instance capture: NeonDrift.Save.PlayerSave.Save @ rva 0x10a0
static void rep_inst_PlayerSave(void *_this) {
    modkit::set_instance(1, _this);
    if (auto fn = reinterpret_cast<void (*)(void *)>(g_orig_inst_PlayerSave)) fn(_this);
}

// ---- instance capture: NeonDrift.Play.PlayerController.Update @ rva 0x1100
static void rep_inst_PlayerController(void *_this) {
    modkit::set_instance(2, _this);
    if (auto fn = reinterpret_cast<void (*)(void *)>(g_orig_inst_PlayerController)) fn(_this);
}

// ---- hook feature NeonDrift.Play.EnemySpawner::Spawn (observe-only)
using Fn_hk_3 = void (*)(void *_this, int32_t a0);
static Fn_hk_3 g_hk3_fn = reinterpret_cast<Fn_hk_3>(g_hk3_orig);
static void hk_3(void *_this, int32_t a0) {
    LOGD("%s hit", g_features[3].key);
    if (g_on[3]) {
        // observe-only: record here, then fall through to the original
    }
    if (g_hk3_fn) g_hk3_fn(_this, a0);
}

// ---- hook feature NeonDrift.Play.PlayerController::TakeDamage (swallow)
using Fn_hk_18 = void (*)(void *_this, float a0);
static Fn_hk_18 g_hk18_fn = reinterpret_cast<Fn_hk_18>(g_hk18_orig);
static void hk_18(void *_this, float a0) {
    LOGD("%s hit", g_features[18].key);
    if (g_on[18]) {
        return;  // swallow: the body is skipped while the feature is on
    }
    if (g_hk18_fn) g_hk18_fn(_this, a0);
}

void apply(size_t index, double value) {
    if (index >= kN) return;
    g_value[index] = value;
    const bool on = value != 0.0;
    g_on[index] = on;
    switch (index) {
    case 0: {  // [const_return] Infinite Ammo
        if (!g_saved_ok[index]) {
            memcpy(g_saved[index], reinterpret_cast<void *>(modkit::rva(0x1210)), 8);
            g_saved_ok[index] = true;
        }
        const uint8_t *dst = on ? g_features[index].patch : g_saved[index];
        if (on && !dst) dst = nullptr;
        if (dst) modkit::patch_memory(modkit::rva(0x1210), dst, 8);
        LOGI("NeonDrift.Play.Weapon::get_Ammo: %s", on ? "patched" : "restored");
        break;
    }
    case 1: {  // [const_return] No Cooldown
        if (!g_saved_ok[index]) {
            memcpy(g_saved[index], reinterpret_cast<void *>(modkit::rva(0x1240)), 8);
            g_saved_ok[index] = true;
        }
        const uint8_t *dst = on ? g_features[index].patch : g_saved[index];
        if (on && !dst) dst = nullptr;
        if (dst) modkit::patch_memory(modkit::rva(0x1240), dst, 8);
        LOGI("NeonDrift.Play.Weapon::GetCooldown: %s", on ? "patched" : "restored");
        break;
    }
    case 2: {  // [const_return] One Hit Kill
        if (!g_saved_ok[index]) {
            memcpy(g_saved[index], reinterpret_cast<void *>(modkit::rva(0x1230)), 12);
            g_saved_ok[index] = true;
        }
        const uint8_t *dst = on ? g_features[index].patch : g_saved[index];
        if (on && !dst) dst = nullptr;
        if (dst) modkit::patch_memory(modkit::rva(0x1230), dst, 12);
        LOGI("NeonDrift.Play.Weapon::GetDamage: %s", on ? "patched" : "restored");
        break;
    }
    case 3: {  // [hook] Log Enemy Spawns
        // callback hk_3 is installed once; g_on[3] gates its body
        LOGI("NeonDrift.Play.EnemySpawner::Spawn: %s", on ? "armed" : "pass-through");
        break;
    }
    case 4: {  // [value_set] Coins → set
        auto *_this = static_cast<char *>(modkit::instance(0));
        if (!_this) { LOGW("%s: no captured instance", g_features[index].key); break; }
        using Fn = void (*)(void*, int32_t);
        if (auto fn = MODKIT_FN(Fn, 0x1410)) fn(_this, (int32_t)value);
        LOGI("NeonDrift.Save.GameOptions::set_Coins -> %g", value);
        break;
    }
    case 5: {  // [const_return] Coins lock
        if (!g_saved_ok[index]) {
            memcpy(g_saved[index], reinterpret_cast<void *>(modkit::rva(0x1400)), 12);
            g_saved_ok[index] = true;
        }
        const uint8_t *dst = on ? g_features[index].patch : g_saved[index];
        if (on && !dst) dst = nullptr;
        if (dst) modkit::patch_memory(modkit::rva(0x1400), dst, 12);
        LOGI("NeonDrift.Save.GameOptions::get_Coins: %s", on ? "patched" : "restored");
        break;
    }
    case 6: {  // [value_set] Gems → set
        auto *_this = static_cast<char *>(modkit::instance(1));
        if (!_this) { LOGW("%s: no captured instance", g_features[index].key); break; }
        using Fn = void (*)(void*, int32_t);
        if (auto fn = MODKIT_FN(Fn, 0x1070)) fn(_this, (int32_t)value);
        LOGI("NeonDrift.Save.PlayerSave::set_Gems -> %g", value);
        break;
    }
    case 7: {  // [const_return] Gems lock
        if (!g_saved_ok[index]) {
            memcpy(g_saved[index], reinterpret_cast<void *>(modkit::rva(0x1060)), 12);
            g_saved_ok[index] = true;
        }
        const uint8_t *dst = on ? g_features[index].patch : g_saved[index];
        if (on && !dst) dst = nullptr;
        if (dst) modkit::patch_memory(modkit::rva(0x1060), dst, 12);
        LOGI("NeonDrift.Save.PlayerSave::get_Gems: %s", on ? "patched" : "restored");
        break;
    }
    case 8: {  // [value_set] Gold → set
        auto *_this = static_cast<char *>(modkit::instance(1));
        if (!_this) { LOGW("%s: no captured instance", g_features[index].key); break; }
        using Fn = void (*)(void*, int32_t);
        if (auto fn = MODKIT_FN(Fn, 0x1050)) fn(_this, (int32_t)value);
        LOGI("NeonDrift.Save.PlayerSave::set_Gold -> %g", value);
        break;
    }
    case 9: {  // [const_return] Gold lock
        if (!g_saved_ok[index]) {
            memcpy(g_saved[index], reinterpret_cast<void *>(modkit::rva(0x1040)), 12);
            g_saved_ok[index] = true;
        }
        const uint8_t *dst = on ? g_features[index].patch : g_saved[index];
        if (on && !dst) dst = nullptr;
        if (dst) modkit::patch_memory(modkit::rva(0x1040), dst, 12);
        LOGI("NeonDrift.Save.PlayerSave::get_Gold: %s", on ? "patched" : "restored");
        break;
    }
    case 10: {  // [field_write] Jumpsleft → write
        auto *_this = static_cast<char *>(modkit::instance(2));
        if (!_this) { LOGW("%s: no captured instance", g_features[index].key); break; }
        int32_t v = (int32_t)value;
        modkit::write_data(reinterpret_cast<uintptr_t>(_this) + 0x2c, &v, 4);
        break;
    }
    case 11: {  // [value_set] Movespeed → set
        auto *_this = static_cast<char *>(modkit::instance(2));
        if (!_this) { LOGW("%s: no captured instance", g_features[index].key); break; }
        using Fn = void (*)(void*, float);
        if (auto fn = MODKIT_FN(Fn, 0x1130)) fn(_this, (float)value);
        LOGI("NeonDrift.Play.PlayerController::set_MoveSpeed -> %g", value);
        break;
    }
    case 12: {  // [const_return] Movespeed lock
        if (!g_saved_ok[index]) {
            memcpy(g_saved[index], reinterpret_cast<void *>(modkit::rva(0x1120)), 8);
            g_saved_ok[index] = true;
        }
        const uint8_t *dst = on ? g_features[index].patch : g_saved[index];
        if (on && !dst) dst = nullptr;
        if (dst) modkit::patch_memory(modkit::rva(0x1120), dst, 8);
        LOGI("NeonDrift.Play.PlayerController::get_MoveSpeed: %s", on ? "patched" : "restored");
        break;
    }
    case 13: {  // [value_set] Level → set
        auto *_this = static_cast<char *>(modkit::instance(1));
        if (!_this) { LOGW("%s: no captured instance", g_features[index].key); break; }
        using Fn = void (*)(void*, int32_t);
        if (auto fn = MODKIT_FN(Fn, 0x1090)) fn(_this, (int32_t)value);
        LOGI("NeonDrift.Save.PlayerSave::set_Level -> %g", value);
        break;
    }
    case 14: {  // [const_return] Level lock
        if (!g_saved_ok[index]) {
            memcpy(g_saved[index], reinterpret_cast<void *>(modkit::rva(0x1080)), 12);
            g_saved_ok[index] = true;
        }
        const uint8_t *dst = on ? g_features[index].patch : g_saved[index];
        if (on && !dst) dst = nullptr;
        if (dst) modkit::patch_memory(modkit::rva(0x1080), dst, 12);
        LOGI("NeonDrift.Save.PlayerSave::get_Level: %s", on ? "patched" : "restored");
        break;
    }
    case 15: {  // [static_write] Unlock Everything
        bool v = (bool)value;
        modkit::write_data(modkit::rva(0x5010), &v, 1);
        break;
    }
    case 16: {  // [const_return] God Mode
        if (!g_saved_ok[index]) {
            memcpy(g_saved[index], reinterpret_cast<void *>(modkit::rva(0x1150)), 8);
            g_saved_ok[index] = true;
        }
        const uint8_t *dst = on ? g_features[index].patch : g_saved[index];
        if (on && !dst) dst = nullptr;
        if (dst) modkit::patch_memory(modkit::rva(0x1150), dst, 8);
        LOGI("NeonDrift.Play.PlayerController::get_IsGodMode: %s", on ? "patched" : "restored");
        break;
    }
    case 17: {  // [toggle] God Mode
        auto *_this = static_cast<char *>(modkit::instance(2));
        if (!_this) { LOGW("%s: no captured instance", g_features[index].key); break; }
        using Fn = void (*)(void*, bool);
        if (auto fn = MODKIT_FN(Fn, 0x1140)) fn(_this, on);
        break;
    }
    case 18: {  // [hook] Ignore Damage
        // callback hk_18 is installed once; g_on[18] gates its body
        LOGI("NeonDrift.Play.PlayerController::TakeDamage: %s", on ? "armed" : "pass-through");
        break;
    }
    case 19: {  // [field_write] Maxhealth → write
        auto *_this = static_cast<char *>(modkit::instance(2));
        if (!_this) { LOGW("%s: no captured instance", g_features[index].key); break; }
        float v = (float)value;
        modkit::write_data(reinterpret_cast<uintptr_t>(_this) + 0x28, &v, 4);
        break;
    }
    case 20: {  // [action] Save Now
        auto *_this = static_cast<char *>(modkit::instance(1));
        if (!_this) { LOGW("%s: no captured instance", g_features[index].key); break; }
        using Fn = void (*)(void*);
        if (auto fn = MODKIT_FN(Fn, 0x10a0)) fn(_this);
        break;
    }
    default: break;
    }
}

size_t feature_count() { return kN; }
const modkit::FeatureDef *features() { return g_features; }
const char *feature_key(size_t i) { return i < kN ? g_features[i].key : ""; }
double peek_feature(size_t i) { return i < kN ? g_value[i] : 0.0; }
void set_feature(size_t i, double v) { apply(i, v); }

bool set_feature_by_key(const char *key, double value) {
    if (!key) return false;
    for (size_t i = 0; i < kN; ++i)
        if (!strcmp(g_features[i].key, key)) { apply(i, value); return true; }
    LOGW("unknown feature key: %s", key);
    return false;
}

double get_feature_by_key(const char *key) {
    for (size_t i = 0; i < kN; ++i)
        if (!strcmp(g_features[i].key, key)) return g_value[i];
    return 0.0;
}

static char g_status[256];
const char *status_line() {
    snprintf(g_status, sizeof(g_status), "base=%p n=%zu on=%zu%s",
             reinterpret_cast<void *>(modkit::self().base), kN,
             static_cast<size_t>(std::count(g_on, g_on + kN, true)),
             modkit::self().found() ? "" : " (module unmapped!)");
    return g_status;
}

static const char *kConfigPaths[] = {
    "/sdcard/Android/data/com.neondrift.game/files/modkit.properties",
    "/data/local/tmp/modkit.properties",
};

void load_defaults() {
    for (const char *path : kConfigPaths) {
        FILE *fp = fopen(path, "re");
        if (!fp) continue;
        char line[256];
        while (fgets(line, sizeof(line), fp)) {
            char *eq = strchr(line, '=');
            if (!eq) continue;
            *eq = 0;
            char *key = line;
            while (*key == ' ' || *key == '\t') ++key;
            if (*key == '#' || !*key) continue;
            const double v = strtod(eq + 1, nullptr);
            for (size_t i = 0; i < kN; ++i) {
                if (!strcmp(g_features[i].key, key)) {
                    g_value[i] = v;
                    g_on[i] = v != 0.0;
                    break;
                }
            }
        }
        fclose(fp);
        LOGI("defaults loaded from %s", path);
        return;
    }
}

void install() {
    if (g_installed) return;
    g_installed = true;
    for (size_t i = 0; i < kN; ++i) {
        g_value[i] = g_features[i].def;
        g_on[i] = (g_features[i].flags & modkit::F_DEFAULT_ON) != 0;
    }
    load_defaults();
    LOGI("install: 21 features, 3 capture hooks, target libil2cpp.so");
    modkit::install_hooks(g_capture_hooks, 3);
    modkit::install_hooks(g_feature_hooks, 2);
    for (size_t i = 0; i < kN; ++i)
        if (g_on[i]) apply(i, g_value[i]);
}

void draw_features_ui() {
#if MODKIT_HAS_IMGUI
    if (!ImGui::BeginTabBar("tabs", ImGuiTabBarFlags_FittingPolicyScroll)) {
        ImGui::TextUnformatted("no features yet");
        return;
    }
    const char *group = nullptr;
    bool open_tab = false;
    bool any_in_tab = false;
    for (size_t i = 0; i < kN; ++i) {
        const modkit::FeatureDef &f = g_features[i];
        if (!group || strcmp(group, f.group)) {
            if (open_tab) ImGui::EndTabItem();
            group = f.group;
            any_in_tab = false;
            open_tab = ImGui::BeginTabItem(group);
        }
        if (!open_tab) continue;
        any_in_tab = true;
        switch (f.kind) {
        case modkit::F_CONST_RETURN:
        case modkit::F_TOGGLE:
        case modkit::F_HOOK: {
            bool on = g_on[i];
            if (ImGui::Checkbox(f.label, &on)) {
                g_on[i] = on;
                apply(i, on ? (f.def != 0.0 ? f.def : 1.0) : 0.0);
            }
            break;
        }
        case modkit::F_VALUE_SET:
        case modkit::F_FIELD_WRITE:
        case modkit::F_STATIC_WRITE:
        case modkit::F_SLIDER: {
            if (f.hi - f.lo <= 1.0) {          // 0/1 range -> a plain switch, not a drag
                bool on = g_value[i] != 0.0;
                if (ImGui::Checkbox(f.label, &on)) apply(i, on ? (f.def != 0.0 ? f.def : 1.0) : 0.0);
                break;
            }
            float v = (float)g_value[i];
            {
                ImGui::PushID((int)i);
                ImGui::TextUnformatted(f.label);
                ImGui::SameLine();
                ImGui::SetNextItemWidth(180.0f);
                if (ImGui::DragFloat("##v", &v, 1.0f, (float)f.lo, (float)f.hi, "%.0f")) {
                    apply(i, v);
                    g_on[i] = v != 0.0;
                }
                ImGui::PopID();
            }
            break;
        }
        default:
            if (ImGui::Button(f.label)) apply(i, f.def);
            break;
        }
        if (f.flags & modkit::F_NEEDS_INSTANCE) {
            ImGui::SameLine();
            ImGui::TextColored(modkit::instance(f.slot) ? ImVec4(0.3f, 1.f, 0.4f, 1.f)
                                                         : ImVec4(1.f, 0.4f, 0.2f, 1.f),
                               "%s", modkit::instance(f.slot) ? "obj" : "no obj");
        }
    }
    if (open_tab) ImGui::EndTabItem();
    ImGui::EndTabBar();
#else
    // Console-only build: dump the feature list to logcat so `adb shell` still drives it.
    for (size_t i = 0; i < kN; ++i)
        LOGI("[%zu] %-34s %-12s = %g", i, g_features[i].key,
             g_features[i].label, g_value[i]);
#endif
}

}  // namespace game

// bridge for modkit's own runtime thread (it must not include game.hpp earlier)
extern "C" void game_install() { game::install(); }
